# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    requires:
      - check
    docker:
      - image: yunion/centos-build:go-1.18.3-0
        environment:
          ONECLOUD_CI_BUILD: "1"

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /root/go/src/yunion.io/x/cloudmux
    parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            make test
            targets="$(circleci tests glob "cmd/*" | circleci tests split)"
            echo $targets | tr ' ' '\n'
            make -j2 $targets
            ls -lh _output/bin/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
